### ISSUE TITLE
road_centre_line layer duplicates geometry when crosses TA

### ISSUE THREAD

**Issue by iharrison** [linz/linz-lds-bde-schema#1]
linz-lds-bde-schema/sql/04-lds_layer_functions.sql

Minor bug where a road crosses a TA boundary the road geometry is doubled up on itself with twice as many nodes than needed. This is due to the geometry being aggregated with ST_Collect. I think the fix is simply not to aggregate the geometry.
Because it's still just one multiline geom nobody has noticed until now.
![image](https://cloud.githubusercontent.com/assets/1088569/17126040/6163b89a-534d-11e6-9d3a-58d235a9856f.png)

**Comment by palmerj** [comment]
@iharrison I'm a little bit blurry on this SQL, but from memory we were trying to create single centrelines for road names aggregating the recorded subsections. Removing the geometry aggregation would stop this I think. Is the issue that some subsections linestring have duplicate overlapping vertices? If so then it's a data issue.

**Comment by iharrison** [comment]
@palmerj Yes issue is duplicate overlapping vertices. I've had a look at the source BDE data and it looks ok. Issue only seems to be with LDS road centrelines. I will do some more testing to be sure.

**Comment by iharrison** [comment]
Update on this. I think the fix is simple:
ST_Collect(**DISTINCT** shape_hex::geometry ORDER BY shape_hex::geometry ASC) AS shape
Just add a DISTINCT to the geometry selection seems to do the trick.
However, I'm still checking as it looks like the order of the linestrings is changed within the multi linestring and need to avoid creating unnecessary changes.

**Comment by iharrison** [comment]
Fix will cause a big changeset. Might as well wait for Aims to replace this.
