### ISSUE TITLE
Drop street_address_ext table

### ISSUE THREAD

**Issue by imincik** [linz/linz-lds-bde-schema#101]
Since addresses are moved from LoL to AIMS, it looks like `street_address_ext` is now obsolete. Current BDE  Processor logs are proving that by reporting this table as empty:

```
2018/05/07 23:56:59 Started creating new version of table street_address_ext
2018/05/07 23:56:59 In task Applying Indexes and constraints, executing SQL: ALTER TABLE street_address_ext ADD CONSTRAINT 2018/05/07 23:56:59 INFO> BdeDatabase.pm:756 - In task Applying Indexes and constraints, executing SQL: ALTER TABLE street_address_ext ADD CONSTRAINT pkey_street_address_ext PRIMARY KEY (id)
2018/05/07 23:56:59 INFO> BdeDatabase.pm:756 - In task Applying Indexes and constraints, executing SQL: CREATE INDEX shx_street_address_ext_shape ON street_address_ext USING gist (shape)
2018/05/07 23:56:59 INFO> BdeDatabase.pm:756 - Finished creating new version of table street_address_ext. 0 rows were created
```

**Comment by imincik** [comment]
@billgeo , can you please confirm that we can drop this table ? Thanks.

**Comment by imincik** [comment]
Another option is just to drop it from BDE Processor DB and keep it in database for backwards compatibility.

**Comment by strk** [comment]
I'm not sure how much linz-lds-bde-schema can be backward compatible
already. Patches exist that add/drop columns, so attempts to load old
BDE files is probably already unsupported ?

**Comment by palmerj** [comment]
@imincik to review. But I think this should be closed without action.

**Comment by imincik** [comment]
I am ok with closing it with no action as well.
