### ISSUE TITLE
Release version 1.4.0

### ISSUE THREAD

**Issue by imincik** [linz/linz-lds-bde-schema#127]
Release version 1.4.0

**Comment by imincik** [comment]
I am un-assigning myself from this task leaving it to @strk .

**Comment by strk** [comment]
Given we're only after bugfixes (for #125), would it make more sense to release 1.3.1 instead ?
See #132

**Comment by strk** [comment]
Please review #136

**Comment by strk** [comment]
Ready: https://github.com/linz/linz-lds-bde-schema/releases/tag/1.4.0
