### ISSUE TITLE
bde_control.bde_TablesAffected function is incorrectly populated with <schema>.<table_name>

### ISSUE THREAD

**Issue by imincik** [linz/linz-lds-bde-schema#130]
bde_control.bde_TablesAffected function is incorrectly populated with <schema>.<table_name>

for example in

https://github.com/linz/linz-lds-bde-schema/blob/00d4959ea15196f9c957f0bb466022b0dd97b0d0/sql/04-lds_layer_functions.sql.in#L1555

but this function doesn't expect schema being provided. This result that function always returns False

/cc @strk

**Comment by palmerj** [comment]
Good catch. Looks like 3fcfbee did a schema prefix blanket change that caused this.

**Comment by strk** [comment]
Yup, and lack of tests for functions missed to catch it earlier (luckly bde-processor-deployment tests are more complete)

**Comment by strk** [comment]
Closed via e18663d85a0d24a5b6d7f388215d3167ad572e06
