### ISSUE TITLE
Avoid mass dropping of functions, which is non isolatable

### ISSUE THREAD

**Issue by strk** [linz/linz-lds-bde-schema#138]
As we found in production, dropping a function does NOT cleanup internal PostgreSQL caches until the transaction is committed, leaving a window open during which cached function OIDs will be dangling, resulting in errors like:

      cache lookup failed for function #######

The only solution to this problem would be to make the OID of the function being dropped survive for the whole transaction, as caches will be invalidated at commit time. This can be done in two ways:

   1. RENAME the old function instead of dropping it, postponing the DROP to a subsequent transaction
   2. Use CREATE OR REPLACE and not drop the function _at_all_

**Comment by imincik** [comment]
This task is still relevant.
