### ISSUE TITLE
Publish updated 1.4 Debian packages to accept PostgreSQL > 9.6

### ISSUE THREAD

**Issue by strk** [linz/linz-lds-bde-schema#143]
See 6d5565c3f6c07fd40f41ff61cf02a305c1c82193

**Comment by strk** [comment]
Branch release-1.4 is ready for that already, since 6d5565c3f6c07fd40f41ff61cf02a305c1c82193

**Comment by imincik** [comment]
Packaged and pushed to `test` branch.
