### ISSUE TITLE
Downgrade INFO messages to NOTICE ?

### ISSUE THREAD

**Issue by strk** [linz/linz-lds-bde-schema#144]
INFO messages cannot be turned off, which is annoying when doing for example tests.
@palmerj any reason for those messages to be at the INFO level rather than the NOTICE level ?

**Comment by palmerj** [comment]
Ok to change them to NOTICE. When I first implemented the code I was not aware that INFO does not have a level and no matter the client_min_message setting will always get reported.

**Comment by strk** [comment]
Great, can you review #145 then ? :)
