### ISSUE TITLE
Lines in Cadastral Adjustments polygon layer

### ISSUE THREAD

**Issue by iharrison** [linz/linz-lds-bde-schema#146]
The cadastral adjustments layer should only ever contain polygon geometries but this weekend's LDS update failed because two line geometries got through.
The ids for the 'bad' geometries are 1656277 and 1663668.

This is the case statement which failed https://github.com/linz/linz-lds-bde-schema/blob/3df3bb048aaa994a7a2a35575163ce5a1e2534fb/sql/04-lds_layer_functions.sql.in#L3515

It seems in this case there were 3 nodes which lined up perfectly so St_ConvexHull created a line rather than a polygon.

I did a quick test and the following code would fix the problem:
```
WITH adjustments AS(
SELECT
        ADJ.id,
        ADJ.adjust_datetime AS date_adjusted,
        SUR.survey_reference,
        count(*) AS adjusted_nodes,
    St_ConvexHull(ST_Collect(NOD.shape ORDER BY NOD.shape ASC)) AS shape
    FROM
        bde.crs_adjustment_run ADJ
        JOIN bde.crs_adjust_method ADM ON ADJ.adm_id = ADM.id
        LEFT JOIN tmp_survey_plans SUR ON ADJ.wrk_id = SUR.wrk_id
        JOIN bde.crs_ordinate_adj ORJ ON ADJ.id = ORJ.adj_id
        JOIN bde.crs_coordinate COO ON ORJ.coo_id_output = COO.id
        JOIN bde.crs_node NOD ON COO.nod_id = NOD.id
    WHERE
        ADJ.status = 'AUTH' AND
        ADM.software_used = 'LNZC' AND
        NOD.cos_id_official = 109
    GROUP BY
        ADJ.id,
        ADJ.adjust_datetime,
        SUR.survey_reference
    ORDER BY
        ADJ.id)
SELECT 
    id, 
    date_adjusted, 
    survey_reference, 
    adjusted_nodes, 
    CASE WHEN ST_geometrytype(shape)='ST_LineString' THEN
        ST_Buffer(shape, 0.00001, 4)
    ELSE
        shape
    END AS shape
FROM adjustments;
```
@strk can you please have a look and advise the best way to fix this. Is there a better way than what I've done above?
We'll then need to create a PR and get a fix deployed - I'm guessing for both old and new gen.

cc/- @imincik @palmerj @JBLINZ

**Comment by palmerj** [comment]
Thanks Ian. Let's discuss tomorrow at the morning.

**Comment by strk** [comment]
See how you like #147 - it also deals with points, using ST_Dimension instead of GeometryType.
