### ISSUE TITLE
Add addition fields to survey plans layers 

### ISSUE THREAD

**Issue by palmerj** [linz/linz-lds-bde-schema#16]
Based on past feedback from LINZ internal and public users the following extra columns would be useful:

REGISTERED_DATE
LODGED_DATE
VALIDATED_DATE
AUTHORISED_DATE
SURVEYOR
FIRM

changes will be something like (but also requires patch added to sql/patches.sql to implement new schema):

``` diff
diff --git a/sql/lds_layer_functions.sql b/sql/lds_layer_functions.sql
index 3adbe07..71b3204 100644
--- a/sql/lds_layer_functions.sql
+++ b/sql/lds_layer_functions.sql
@@ -2606,6 +2606,7 @@ BEGIN
                     'crs_sys_code',
                     'crs_transact_type',
                     'crs_vector',
+                    'crs_user',
                     'crs_work'
                 ],
                 'any affected'
@@ -2698,6 +2699,12 @@ BEGIN
             description,
             status,
             survey_date,
+            registered_date,
+            lodged_date,
+            validated_date,
+            authorised_date,
+            surveyor,
+            firm,
             purpose,
             type,
             datum,
@@ -2714,14 +2721,22 @@ BEGIN
             SUR.description,
             SCO2.char_value AS status,
             SUR.survey_date,
+            SUR.registered_date,
+            WRK.lodged_date,
+            WRK.validated_date,
+            WRK.authorised_date,
+            COALESCE(PRIN.given_names || ' ', '') || PRIN.surname as surveyor,
+            FIRM.corporate_name as firm,
             SCO1.char_value AS purpose,
             TRT.description AS type,
-            COALESCE(DTM.name, 'UNKNOWN') AS datum,
+            COALESCE(DTM.name, 'Unknown') AS datum,
             ST_Collect(SPF.shape ORDER BY SPF.shape ASC) AS shape
         FROM
             crs_survey SUR,
             crs_work WRK
-                LEFT JOIN tmp_proxy_datum DTM ON (WRK.cos_id = DTM.cos_id),
+                LEFT JOIN tmp_proxy_datum DTM ON (WRK.cos_id = DTM.cos_id)
+                LEFT JOIN crs_user FIRM ON (WRK.usr_id_firm = FIRM.id)
+                LEFT JOIN crs_user PRIN ON (WRK.usr_id_principal = PRIN.id),
             crs_sur_plan_ref SPF,
             crs_transact_type TRT,
             crs_sys_code SCO1,
@@ -2740,7 +2755,7 @@ BEGIN
             SPF.shape IS NOT NULL AND
             WRK.restricted = 'N'
         GROUP BY
-            1, 2, 3, 4, 5, 6, 7, 8, 9
+            1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15
         ORDER BY
             WRK.id;

diff --git a/sql/lds_layer_tables.sql b/sql/lds_layer_tables.sql
index 060f018..77dc9cb 100644
--- a/sql/lds_layer_tables.sql
+++ b/sql/lds_layer_tables.sql
@@ -651,6 +651,12 @@ CREATE TABLE survey_plans (
     description VARCHAR(2048),
     status VARCHAR(2048) NOT NULL,
     survey_date DATE,
+    registered_date DATE,
+    lodged_date TIMESTAMP,
+    validated_date DATE,
+    authorised_date TIMESTAMP,
+    surveyor VARCHAR(100),
+    firm VARCHAR(100),
     purpose VARCHAR(2048) NOT NULL,
     type VARCHAR(100) NOT NULL,
     datum VARCHAR(10)

```

**Comment by palmerj** [comment]
Moved from https://github.com/linz/linz_bde_uploader/issues/18

**Comment by strk** [comment]
My understanding is that if we use patches we need to *only* put the alter table in the patches and not modify the starting table at all, am I wrong ?

**Comment by strk** [comment]
btw, if we add columns in patches the comments file would need to be applied *after* the patches, or if a column comment is added we'd end up with missing column at the time a comment for it is added...

**Comment by strk** [comment]
also what happens with table_version upon adding columns ? shall we postpone this issue so to be able to close 1.1.0 in a short time ?

**Comment by palmerj** [comment]
> My understanding is that if we use patches we need to only put the alter table in the patches and not modify the starting table at all, am I wrong ?

That's the current process.

**Comment by palmerj** [comment]
> also what happens with table_version upon adding columns ? shall we postpone this issue so to be able to close 1.1.0 in a short time ?

table_version support this operation via `ver_versioned_table_add_column()`

**Comment by strk** [comment]
@palmerj as I plan to close 1.2.0 release I tried your patch but it doesn't apply in master branch. For example `authorised_date` is already there. Do you plan to make a PR for this ?

**Comment by palmerj** [comment]
Will keep this open as customer feature request. For @JBLINZ information.

**Comment by strk** [comment]
Is this change still desired ?

**Comment by billgeo** [comment]
@iharrison are you able to comment on the business drivers for this?

**Comment by iharrison** [comment]
Sorry @billgeo, we can't remember where this request initially came from. I don't think it's a priority.

**Comment by billgeo** [comment]
I think we should close this issue as it originally came up in 2012 and there seems to be no current business driver for it. If it becomes a priority we can open a new ticket for it.
