### ISSUE TITLE
Publish Bionic packages

### ISSUE THREAD

**Issue by strk** [linz/linz-lds-bde-schema#164]
Once tested (#141)

**Comment by imincik** [comment]
This task is still relevant.

**Comment by imincik** [comment]
This task is still relevant.

**Comment by strk** [comment]
linz-lds-bde-schema_1.6.0-1linz~bionic1_all.deb published to test repository
Keeping open until promoted to production

**Comment by imincik** [comment]
@strk , we are promoting packages from `test` repo branch to `prod` after BDE Processor UAT is done (https://github.com/linz/bde-processor-deployment/wiki/Production-Deployment#production-deployment). I think we don't need this ticket. Will close it.
