### ISSUE TITLE
LDS_MaintainSimplifiedParcelLayers runs when changes occur in unused tables

### ISSUE THREAD

**Issue by strk** [linz/linz-lds-bde-schema#165]
While trying to find possible UTF8 sources in LDS tables, I stumbled upon what looks like being an over-sensibility of `LDS_MaintainSimplifiedParcelLayers`, which is coded to only trigger regeneration of tables when changes occurred, for the given upload identifier, in a set of tables.

Of the set of tables, not all of them seem to be really used in the queries generating the output table, thus making such tables not worth checking for updates.

Full list of tables checked for changes:
                    'crs_affected_parcl',
                    'crs_appellation', 
                    'crs_estate_share',
                    'crs_legal_desc',
                    'crs_legal_desc_prl',
                    'crs_locality',
                    'crs_parcel',
                    'crs_proprietor',
                    'crs_stat_act_parcl',
                    'crs_statute',
                    'crs_statute_action',
                    'crs_survey',
                    'crs_sys_code',
                    'crs_title',
                    'crs_title_estate',
                    'crs_ttl_hierarchy',
                    'crs_topology_class',
                    'crs_work',
                    'cbe_title_parcel_association'

Of the above, I can not find other references, in the `04-lds_layer_functions.sql.in`, of the following tables:

                    'crs_appellation', 
                    'crs_legal_desc_prl',
                    'crs_statute',
                    'crs_statute_action',
                    'crs_ttl_hierarchy',

Shall we skip checking those 5 tables then ? \cc @palmerj

**Comment by imincik** [comment]
Thanks @strk , interesting finding.

**Comment by strk** [comment]
If you want  you can review https://github.com/linz/linz-lds-bde-schema/pull/166 :)

**Comment by palmerj** [comment]
```
'crs_appellation', 
'crs_legal_desc_prl',
'crs_statute',
'crs_statute_action',
```
I think these tables are needed because they are used in bde functions: https://github.com/linz/linz-bde-schema/blob/master/sql/03-bde_functions.sql.in

```
'crs_ttl_hierarchy',
```

Not sure about this one. A deeper investigation might be required:
