### ISSUE TITLE
Update NZ WACA Adjustments layer function to include all WACA adjustments

### ISSUE THREAD

**Issue by iharrison** [linz/linz-lds-bde-schema#174]
The LDS layer https://data.linz.govt.nz/layer/50836-nz-waca-adjustments/ has not be updated for some time. This is because the where clause at https://github.com/linz/linz-lds-bde-schema/blob/76237a3c964a3e83d3edcd8009674da6ae3dbd38/sql/04-lds_layer_functions.sql.in#L3675 needs to be changed to pick up any adjustment method name that contains the word 'WACA'.
Geodetic say that new methods are added over time but WACA methods will always contain 'WACA' in the crs_adjust_method.name field.
So `ADM.name ilike '%WACA%' ` would work.

**Comment by palmerj** [comment]
Sounds reasonable to do in this release as it's such a small change. @strk can you please add to release 1.2 and create a fix?

**Comment by iharrison** [comment]
Still relevant

**Comment by iharrison** [comment]
We forgot to add this to the 1.2 release. @imincik @strk @palmerj can we fit this in for BDE Processor 1.3?

**Comment by palmerj** [comment]
Not sure, given we now have another BDE processor outage and the logical replication feature is still needed more work.

**Comment by iharrison** [comment]
Still relevant

**Comment by iharrison** [comment]
Still relevant

**Comment by iharrison** [comment]
Still relevant

**Comment by iharrison** [comment]
Still relevant

**Comment by iharrison** [comment]
Still relevant

**Comment by iharrison** [comment]
Still relevant

**Comment by billgeo** [comment]
Hi @iharrison can you please confirm business need for this. Are we missing data in LDS etc? Or something else.

**Comment by iharrison** [comment]
Yes missing data in LDS. It's a very small change and would be good to prioritise a business need!

**Comment by billgeo** [comment]
Okay, will include it in BDE 1.4 (the next one) release.

**Comment by iharrison** [comment]
Some business context: This table has the extents of the data incorporated into an adjustment which has been completed as a Wide Area Cadastral Adjustment (WACA). It's useful for customers and in particular surveyors to see if an area has been covered by an adjustment.
At the moment the majority of the adjustments are missing from the layer.

**Comment by imincik** [comment]
@strk ,

We are still missing one name "WACA: SDC Area v1.0" so to catch this as well can you please remove the space. i.e. ADM.name ilike '%WACA%' not ADM.name ilike '%WACA %'

**Comment by strk** [comment]
I filed #203 to further fix this. Let's wait for @iharrison to review, this time. It'll need to go to 1.8.2

**Comment by strk** [comment]
Fixed via https://github.com/linz/linz-lds-bde-schema/pull/204
