### ISSUE TITLE
Add possibility to set data tables to read-only mode to loader script

### ISSUE THREAD

**Issue by imincik** [linz/linz-lds-bde-schema#187]
Add possibility to set data tables to read-only mode to loader script

**Comment by imincik** [comment]
Hi @strk , are you able to work on this ticket ?

**Comment by strk** [comment]
> Hi @strk , are you able to work on this ticket ?

Once https://github.com/linz/linz-bde-schema/pull/162 is merged, so
we have an accepted method to do it, and will be done for all repos.
