### ISSUE TITLE
Add functions documentation

### ISSUE THREAD

**Issue by strk** [linz/linz-lds-bde-schema#19]
This project contains 22 functions, but there's no documentation about their usage, so writing tests (#18) is not possible due to lack of expected behavior information.

I could extrapolate documentation from current behavior, detected by writing tests.
@imincik let me know if you want me to take this path (or there's some documentation elsewhere)

**Comment by imincik** [comment]
> I could extrapolate documentation from current behavior, detected by writing tests.

My opinion is, that you should not try to write documentation to this.

**Comment by palmerj** [comment]
Still relevant.
