### ISSUE TITLE
Publish packages for 1.8.2

### ISSUE THREAD

**Issue by strk** [linz/linz-lds-bde-schema#202]
When [ready](#201)

**Comment by strk** [comment]
Release ready for packaging: https://github.com/linz/linz-lds-bde-schema/releases/tag/1.8.1

**Comment by strk** [comment]
Not worth publishing 1.8.1, let's wait for 1.8.2 instead

**Comment by strk** [comment]
https://github.com/linz/linz-lds-bde-schema/issues/205 is the ticket to _release_ 1.8.2

**Comment by strk** [comment]
Release ready to publish: https://github.com/linz/linz-lds-bde-schema/releases/tag/1.8.2

**Comment by imincik** [comment]
Packaged and uploaded to `test` repo branch.
