### ISSUE TITLE
Release 1.9.1

### ISSUE THREAD

**Issue by imincik** [linz/linz-lds-bde-schema#211]
### DEBIAN PACKAGE: linz-lds-bde-schema

Last tag: debian/1.9.0-1linz_bionic1
commit 9f87ff25baec95c84005a41e6d5f9ab7b53a0e62
Author: Ivan Mincik <imincik@linz.govt.nz>
Date:   Tue Feb 11 15:00:08 2020 +0100

    [debian] Changelog update

New changes since last tag:
```
commit 377c88d9f497a61292adfa5c3cd80af4078f3622
Author: Sandro Santilli <strk@kbt.io>
Date:   Wed Mar 4 14:47:16 2020 +0100

    Do not assume too much on tableversion/dbpatch loader errors
    
    They don't necessarely mean lack of stdout support, so check if
    that's the case
    
    Fixes #209

commit 5ba5bd50f6a3a20dd24d6e0be73b0592ecae365c
Author: Ivan Mincik <imincik@linz.govt.nz>
Date:   Tue Feb 11 15:00:08 2020 +0100

    [debian] Changelog update
```

**Comment by strk** [comment]
Such small change should probably go in a 1.9.1 release. Note we still haven't branched off, nor I changed the target version in Makefile. These usually are waiting for packaging to be completed to avoid conflicts on your side.

Packaging completed in #208 so I think we could move on.

If you agree with that I would postpone branching to when we really need it, so I could cut a 1.9.1 release out of current master (appropriately retargetting the Makefile here).

**Comment by imincik** [comment]
Please release version 1.9.1

**Comment by imincik** [comment]
Now we need to release because of this https://github.com/linz/linz-lds-bde-schema/pull/213

**Comment by imincik** [comment]
Considering that we are now in big delay with BDE Processor UAT, I packaged `linz-bde-schema` without those small changes. We can wait with this release too as well.
