### ISSUE TITLE
linz-lds-bde-schema-load: pg_config: not found

### ISSUE THREAD

**Issue by imincik** [linz/linz-lds-bde-schema#216]
With current bde-processor-deployment and packaging we are missing `pg_config`. 

```
INFO: BDE Processor started at 2020-04-14T20:47:52+12:00
bde_prepare_db: Loading dbpatch 1.5.0 in -._patches (EXT_MODE off)
bde_prepare_db: /usr/bin/linz-lds-bde-schema-load: 1: /usr/bin/linz-lds-bde-schema-load: pg_config: not found
```

I think, we can drop [this](https://github.com/linz/linz-lds-bde-schema/blob/master/scripts/linz-lds-bde-schema-load.in#L72) step. @strk , if you agree to drop, we need to do it in other packages where we do the same.

**Comment by strk** [comment]
Uhm, I'll have to check why we need pg_config in the first place, I belive it was about finding the 
scripts directory but we already accounted for them NOT being there, so we _might_ add more tolerability (tolerate absence of pg_config). I suppose the same thing would happen on different loaders so it'll be something to enhance in multiple repos. Will check them all and file PRs for each I find offending.
