### ISSUE TITLE
Undocumented dependency on linz_bde_uploader

### ISSUE THREAD

**Issue by strk** [linz/linz-lds-bde-schema#22]
I installed the schema to test LDS.LDS_TableHasData function but found that it depends on a `bde_control` schema, which is part of `linz_bde_uploader` sql script.

The dependency is not documented.

This is the kind of things that would emerge by adding actual tests (#18)

**Comment by strk** [comment]
Exact error message:
```
linz=# select LDS.LDS_TableHasData('lds', 'geodetic_marks');
ERROR:  schema "bde_control" does not exist
LINE 1: SELECT bde_control.bde_TableOid(p_schema, p_table_name)
               ^
QUERY:  SELECT bde_control.bde_TableOid(p_schema, p_table_name)
CONTEXT:  PL/pgSQL function lds.lds_gettable(name,name) line 5 at assignment
```

**Comment by palmerj** [comment]
Yip linz_bde_uploader is required for the bde_control.* support functions. So the dependancy should be documented.

**Comment by imincik** [comment]
@palmerj , @strk ,

Isn't it little bit strange that  `linz-lds-bde-schema` depends on `linz_bde_uploader`. It should be other way around.

Isn't it solvable by moving few functions between those packages or creating some new one ?

**Comment by palmerj** [comment]
Sort off. Mostly  should just depend on linz_bde_uploader due to the bde_control.* public API usage requirements. At the moment the only real dependencies linz_bde_uploader has on linz-lds-bde-schema is via the config which has a call to the simple and full bde function calls. Maybe it's that config piece that could be taken out of linz_bde_uploader and placed into bde-processor-deployment only?

**Comment by imincik** [comment]
> At the moment the only real dependencies linz_bde_uploader has on linz-lds-bde-schema is via the config which has a call to the simple and full bde function calls.

@palmerj , I am not sure if I understand you.
I am talking about other way around dependency - linz-lds-bde-schema depending on linz_bde_uploader which we should probably avoid.

**Comment by palmerj** [comment]
Why? linz_bde_uploader has a public API and we need to use it in this package. Those linz_bde_uploader functions that provide the public API are used in other packages including linz_bde_uploader itself and shouldn't be copied out to this or some other place.

**Comment by imincik** [comment]
OK, @palmerj .
