### ISSUE TITLE
ERROR:  column "lodged_date" of relation "lds.survey_plans" does not exist

### ISSUE THREAD

**Issue by strk** [linz/linz-lds-bde-schema#224]
Testing the 1.10.0 schema loader against RDS, after the fix in #223 - results in this error message:
```
ERROR:  column "lodged_date" of relation "lds.survey_plans" does not exist
```

**Comment by strk** [comment]
The STATEMENT triggering the ERROR is a `CREATE COMMENT` statement.
The `lodged_date` field of `lds.survey_plans` table is created by a patch named `BDE - 1.0.2: Create survey tables and columns for pending parcels release`.

The PATCH runs BEFORE the `CREATE COMMENT`, so I'm not sure what's going on

Or, as I write, maybe I know: I run `DROP SCHEMA lds CASCADE` which obviously did NOT cascade to patches, so the patch was NOT applied... We really need a way to "unload" the schema.

**Comment by imincik** [comment]
@strk , why this ticket was closed ? Problem doesn't exist anymore ?

**Comment by strk** [comment]
It was an invalid one, as written in the last paragraph of my previous comment. I used `DROP SCHEMA lds CASCADE` on the database, which left `applied_patches` table from `dbpatch` untouched, which meant those patches would not be applied again on next schema load. It's nice if we want to provide a way to uninstall (would need to take care of both dbpatch and tableversion) but this ticket in itself is an invalid one.

**Comment by imincik** [comment]
Thanks @strk . I understand now.
