### ISSUE TITLE
Update Data Dictionaries / Docs

### ISSUE THREAD

**Issue by billgeo** [linz/linz-lds-bde-schema#229]
Data Dictionaries on LDS are 1 or 2 versions ahead of the versions in this repository.
v1.6 https://data.linz.govt.nz/document/11012-property-and-ownership-simplified-tables-data-dictionary/
v1.5 https://github.com/linz/linz-lds-bde-schema/blob/master/doc/property-and-ownership-simplified-tables-data-dictionary.md
 
v2.6 https://data.linz.govt.nz/document/11095-lds-full-landonline-data-dictionary-and-models/
v2.4 https://github.com/linz/linz-lds-bde-schema/blob/master/doc/lds-full-landonline-data-dictionary-and-models.md

- [x] LINZ should update the docs in this repo
- [ ] developers should make sure that the tools/processes to do this are usable by the LDS team and they are aware that this is the source for the docs now.

**Comment by billgeo** [comment]
Also need to add new vertical datum column in CRS Work

**Comment by strk** [comment]
the md files should be downloaded under the doc/ directory, replacing the current ones, then simply running `make` should result in having the generated comments up-to-date. Files currently used are:
 - property-and-ownership-simplified-tables-data-dictionary.md
 - lds-full-landonline-data-dictionary-and-models.md

Those files, currently in repository, might have been manually edited by Ashleigh Ross to have a usable formatting. The information about the kind of formatting is in the [doc](https://github.com/linz/linz-lds-bde-schema/tree/master/doc) directory

**Comment by strk** [comment]
Do we have similar markdown documents to implement https://github.com/linz/linz-bde-schema/issues/200 ?
For reference, the commit in which Ashleigh implemented automatic generation is 0e3e38f7a8fa116a110d9d1bfe3ce56ed7cd6652

**Comment by strk** [comment]
Ah, now I see, the source document is a PDF, not an .md !
Note that the .md files in the source tree of this repository CAN be converted to PDF. The idea was to make the files in THIS repository to BE the source, and publish the generated PDFs.

To build the PDFs, from top-level dir run:
> make docs

The wkhtmltopdf tool needs to be installed for that to work.

**Comment by strk** [comment]
Note that a github action is already building the PDFs so we might think of a way to also automatically publish them...

**Comment by billgeo** [comment]
> now I see, the source document is a PDF, not an .md

Yes. I think the steps needed will be:

1.  Update the MD files in the repo with the changes from the newer version PDFs (or the source docs for these - probably MS Word. Will need to check with @vlindsay about that).
2. Set up GH actions to automatically publish PDFs to LDS when there is a change (I think this is a good idea)
3. Discuss with LDS team about updating the MD in the repo (as the source of the document), and not using some other process/tool like MS Word.

Is my understanding correct?

**Comment by vlindsay** [comment]
Latest Word versions of dictionaries are in objective
 
- Ful LoL doc: https://linzone/id:A1665627

- Simplified doc: https://linzone/id:A1313685

**Comment by strk** [comment]
@vlindsay according to a [comment](https://github.com/linz/linz-bde-schema/issues/54#issuecomment-347681119) by @palmerj the actual source of that information is an XML file, not a PDF file, do you also have links to those XML files ?

**Comment by strk** [comment]
Also, in #73 @Ashleigh234 submitted markdown versions, but there's no trace of how the markdown was generated from the PDF or XML (whatever she got). Do you remember about that, Ashleigh ?

**Comment by billgeo** [comment]
Hi @strk 

> do you also have links to those XML files ?

The LDS team updated those documents manually. So to resolve this issue, I think we should manually update the MD versions in this repo. Changes should be pretty minimal. Not sure if you can diff a PDF but that might help identify the changes? Otherwide maybe @vlindsay can indicate what has changed between versions?

Once this task is completed, we can use the MD versions as the source of truth from now on.

Also, @Ashleigh234 doesn't work at LINZ anymore.

**Comment by strk** [comment]
It would be great to have detailed diff listed. I can try to obtain them myself (can diff a txt rendering of the PDF).
Can you include 2.4 PDF version of data dictionary and and 1.5 PDF version of simplified tables dictionary ?
Meanwhile I've done some manual work to extract BDE tables docs from the 2.6 data dictionary in https://github.com/linz/linz-bde-schema/pull/215

**Comment by strk** [comment]
Also, I'm thinking it could be useful to store these MD files in their own repository because the same MD files could be used for documenting tables in BDE schema (see https://github.com/linz/linz-bde-schema/pull/215)

**Comment by strk** [comment]
Well I went ahead and started manual work on editing the markdown. The ongoing work is in a branch of this repository ('updated-docs'), and is tracked by PR #242 -- my suggestion is for @vlindsay to see if she can edit the relevant file (https://github.com/linz/linz-lds-bde-schema/blob/updated-docs/doc/lds-full-landonline-data-dictionary-and-models.md) to help with the update (see the pencil icon on top-right corner).

**Comment by billgeo** [comment]
> Also, I'm thinking it could be useful to store these MD files in their own repository because the same MD files could be used for documenting tables in BDE schema (see [linz/linz-bde-schema#215](https://github.com/linz/linz-bde-schema/pull/215))

This sounds logical. Could they go into bde-processor-deployment though?

**Comment by billgeo** [comment]
> Well I went ahead and started manual work on editing the markdown.

Thanks @strk . @vlindsay I can show you what file/url to edit and the basics of Markdown.

**Comment by strk** [comment]
The text part is completed, ticket #247 is for the images part

**Comment by strk** [comment]
Update of images is ready for review in #248

**Comment by strk** [comment]
Docs were updated, closing this
