### ISSUE TITLE
LDS.LDS_MaintainSimplifiedLayers depends on bde_upload_X schema

### ISSUE THREAD

**Issue by strk** [linz/linz-lds-bde-schema#23]
I wanted to try running LDS_MaintainSimplifiedLayers manually but found out it attempts to read from an `_options` table in a schema which is created by the `bde.bde_CreateUpload` function found in `linz-bde-schema`. It could be more useful if source and target schema names could be passed as parameters, to give more opportunities to run independently from other processes and thus allow for isolated testing/profiling.

**Comment by strk** [comment]
Sorry, the `bde_CreateUpload` is in the `bde_control` schema, and is installed by `linz_bde_uploader`, adding another dependency as already reported in #22

**Comment by palmerj** [comment]
Ok see the problem. Not sure I fully understand the solution you are proposing. The issue is many function calls in the main function rely on upload_id aware function from bde_control.* e.g bde_control.bde_GetOption, bde_control.bde_TablesAffected or bde_control.bde_ExecuteSqlArray.

**Comment by strk** [comment]
Then clearly my solution would not work. I'm looking for a way to posticipate running `LDS_MaintainSimplifiedLayers` - maybe there's a way to request the uploader NOT to drop the temporary uploader schema ?

**Comment by palmerj** [comment]
> maybe there's a way to request the uploader NOT to drop the temporary uploader schema ?

Currently there isn't. It would require either:

- an additional cli option for linz_bde_uploader and then having that passed to down through [BdeUpload.pm](https://github.com/linz/linz_bde_uploader/blob/master/lib/LINZ/BdeUpload.pm#L846) -> [BbeDatabase.pm](https://github.com/linz/linz_bde_uploader/blob/master/lib/LINZ/BdeDatabase.pm#L426) ->  [bde_FinishUpload](https://github.com/linz/linz_bde_uploader/blob/master/sql/02-bde_control_functions.sql#L338) and altering the bde_FinishUpload function to not delete the tmp bde upload schema
- More a simple option is to just an a SQL global custom configuration and bde_FinishUpload/_bde_ReleaseLocks checks if it's set and doesn't delete the schema.

**Comment by strk** [comment]
Or maybe portions of code called by `LDS_MaintainSImplifiedLayers` could be made available stand-alone for testing. I guess all the code that creates valid geometries is going to be the most expensive one

**Comment by palmerj** [comment]
> Or maybe portions of code called by LDS_MaintainSImplifiedLayers could be made available stand-alone for testing.

Could do. But probably take longer to implement.

> I guess all the code that creates valid geometries is going to be the most expensive one

That's definitely part of it. I also think a lot of the joining, sorting and aggregation takes a lot of time.

**Comment by strk** [comment]
For keeping the temporary uploader schema, how about something like this:
```
    -- Drop the schema used by the lock                                         
    IF bde_GetOption(p_upload, 'keep_temp_schema') IS NULL; THEN                
        EXECUTE 'DROP SCHEMA IF EXISTS ' || bde_TmpSchema(p_upload) || ' CASCADE';
    END IF; 
```

Then using the `_finishSql` configuration to set that option ?

**Comment by palmerj** [comment]
Given the low usage that will be ok to set SQL global option via the db_upload_complete_sql config.

**Comment by strk** [comment]
`db_upload_complete_sql` works fine for that. PR with automated test ready:
https://github.com/linz/linz_bde_uploader/pull/115
