### ISSUE TITLE
Rebuild Debian packages

### ISSUE THREAD

**Issue by imincik** [linz/linz-lds-bde-schema#230]
Rebuild Debian packages created by older automated packaging version.

**Comment by strk** [comment]
Tag 1.10.2 [pushed](https://github.com/linz/linz-lds-bde-schema/releases/tag/1.10.2), which triggered [github action](https://github.com/linz/linz-lds-bde-schema/runs/775518318?check_suite_focus=true) building and publishing [package](https://packagecloud.io/linz/test/packages/ubuntu/bionic/linz-lds-bde-schema_1.10.2-linz~bionic_all.deb), committing and pushing [changelog changes](https://github.com/linz/linz-lds-bde-schema/commit/d3cbb8b2819c554a32f3b540b062884c5864c10a) and corresponding [debian tag](https://github.com/linz/linz-lds-bde-schema/releases/tag/debian%2F1.10.2-linz_bionic)
