### ISSUE TITLE
Add mortgage instrument types to logic that masks memorial text for protected Titles under the Family Violence Act

### ISSUE THREAD

**Issue by iharrison** [linz/linz-lds-bde-schema#251]
The LTA 2017 required the ability to mask encumbrancee names in title instruments. In the Landonline data we publish on the LDS these names can appear in the encumbrancee table and the title memorial/title memorial text tables.

No changes to the BDE Processor to mask title memorial/memorial text tables was done for the LTA as the BDE Processor already masks these tables as part of the existing Family Violence Act rules. However, it's come to light that there is an shortcoming with the existing masking rules as mortgage memorials are not masked in the table https://data.linz.govt.nz/table/52007-landonline-title-memorial-text/

To fix need to add the codes `'DMM','M','MEM','TM','TMEM','DM','CNMG','MM','MP','MVM','MFL','PDM'` to the line https://github.com/linz/linz-lds-bde-schema/blob/63d4ed497c36b6c42fb0b892327f794ef6ad784a/sql/06-bde_ext_functions.sql.in#L373
i.e. it should be: `type IN ('JFH','DD','CN','UAPP','X','T','TSM','DMM','M','MEM','TM','TMEM','DM','CNMG','MM','MP','MVM','MFL','PDM')`

**Comment by imincik** [comment]
Fixed by #252
