### ISSUE TITLE
unused upload_id parameter in LDS_CreateTitleExclusionTables and LDS_DropTitleExclusionTables functions

### ISSUE THREAD

**Issue by strk** [linz/linz-lds-bde-schema#29]
While writing SQL to test simplified layers creation in isolation I found that `LDS_DropTitleExclusionTables` and `LDS_CreateTitleExclusionTables` are expected to take a parameter (`upload_id`) but do not use it.

Is there a plan to make use of it or should it be dropped ?

**Comment by strk** [comment]
Same happens with LDS_CreateSurveyPlansTable

**Comment by imincik** [comment]
Personally I have no idea ...

**Comment by palmerj** [comment]
Just saw this old issue. 

Mostly likely upload_id is not needed in many of the functions now, unless a linz_bde_upload function is required like bde_control.bde_GetOption or bde_control.bde_TablesAffected. Back in 2012 logging statement in the SQL functions used by a SQL function `bde_control.upload_log` which required to the upload_id to load to the upload session log file, so it was almost a default that any SQL functions need to pass the upload_id around. But that was removed and replaced with simple SQL RAISE commands.
