### ISSUE TITLE
Speed up  LDS.LDS_MaintainSimplifiedParcelLayers

### ISSUE THREAD

**Issue by strk** [linz/linz-lds-bde-schema#30]
See https://github.com/linz/bde-processor-deployment/wiki/MaintainSimplifiedParcelLayers-Profiling-2017

The idea is to avoid querying `crs_appellation` for each record in `crs_parcel` (we're talking tens of millions here).

Current code triggers not one but *2* queries of that table for each record, due to a suboptimal `bde_get_combined_appellation` function defined in `linz-bde-schema` which is going to be  improved by https://github.com/linz/linz-bde-schema/pull/36.

This issue is to rewrite the query that creates `tmp_parcels` so to avoid calling the `bde_get_combined_appellation` function completely but rather directly call the new `bde_get_app_specific` function taking a `crs_appellation` record. Doing so would drop both nested scans.

Expected speedup is in the order of x8 (it should take 1/8 of the time to complete)

NOTE: such speedup will depend on availability of the newfunction in `linz-bde-schema` so will only be possible when version 1.1.0 or later of the schema is available

**Comment by strk** [comment]
\cc @imincik @palmerj

**Comment by imincik** [comment]
Sounds great @strk

**Comment by strk** [comment]
The `crs_appellation` query reduction was merged (https://github.com/linz/linz-bde-schema/pull/36) so I'm closing this
