### ISSUE TITLE
Weird construct to create  LDS_GetProtectedText function

### ISSUE THREAD

**Issue by strk** [linz/linz-lds-bde-schema#34]
Reading the `04-lds_layer_function.sql.in` file I found this weird construct:
```
 DO $$
BEGIN

IF NOT EXISTS(SELECT * from pg_proc where proname = 'lds_getprotectedtext') THEN

EXECUTE '
CREATE FUNCTION LDS_GetProtectedText(
    p_text VARCHAR(20)
)
RETURNS
    TEXT AS
$FUNC$
    SELECT ''''::VARCHAR;
$FUNC$ LANGUAGE sql;
';

ALTER FUNCTION LDS_GetProtectedText(VARCHAR(20)) OWNER TO bde_dba;

END IF;
END;
$$;
```

Why not using the `CREATE OR REPLACE FUNCTION` as done elsewhere ? There's no comment saying why the weird construct is used.

Ideas @palmerj ?

**Comment by imincik** [comment]
Maybe some obsolete code from very old PostgreSQL times ?

**Comment by strk** [comment]
I would change it to conform to the rest, unless there's another reason. The only I could think of is if we want to allow users to define their own `lds_GetProtectedText` before loading the .SQL of this project. Is that a valid use case ?

**Comment by imincik** [comment]
I think only @palmerj can answer this. Jeremy, would you please have a look ?
