### ISSUE TITLE
Document (or drop) dependency on territorial admin boundary data

### ISSUE THREAD

**Issue by strk** [linz/linz-lds-bde-schema#4]
As reported in https://github.com/linz/bde-processor-deployment/issues/17#issuecomment-302995691 there's a dependency of  [LDS.LDS_MaintainSimplifiedElectoralLayers](https://github.com/linz/linz-lds-bde-schema/blob/master/sql/04-lds_layer_functions.sql#L3296) PL/Pgsql function on the presence of a  `territorial_authority` table. Such dependency is not documented.

This ticket is to add information about the dependency and how to satisfy it, or to drop it as suggested by @palmerj.

**Comment by strk** [comment]
If I undertood correctly the LDS.LDS_MaintainSimplifiedElectoralLayers function could be drop and replaced by an import of simplified electoral layers generated on a different system (AIMS).
It might help to drop a link here about the simplified electoral layers as found in AIMS \cc @SPlanzer

**Comment by palmerj** [comment]
> If I understood correctly the LDS.LDS_MaintainSimplifiedElectoralLayers function could be dropped and replaced by an import of simplified electoral layers generated on a different system (AIMS).

I vote for it to be dropped as the electoral/addressing data is no longer maintained in Landonline, and all addressing data is now sourced from the AIMS production database.

As you can see in [table.conf](https://github.com/linz/linz_bde_uploader/blob/master/conf/tables.conf#L175) we already have a comment that addressing files are no longer unloaded by the BDE export.
```
TABLE   crs_road_ctr_line            key=id          row_tol=0.20,0.95   files rcl1 # no longer unloaded from 8/12/2016
TABLE   crs_road_name                key=id          row_tol=0.20,0.95   files xrna # no longer unloaded from 8/12/2016
TABLE   crs_road_name_asc            key=audit_id    row_tol=0.20,0.95   files rns # no longer unloaded from 8/12/2016
TABLE   crs_street_address           key=id          row_tol=0.20,0.95   files xsad # no longer unloaded from 8/12/2016
```

Also these electoral files are also no longer exported in Landonline BDE (but not commented on)
```
TABLE   crs_mesh_blk                 key=id          row_tol=0.20,0.95   files mbk1
TABLE   crs_mesh_blk_area            key=audit_id    row_tol=0.20,0.95   files mba
TABLE   crs_mesh_blk_bdry            key=audit_id    row_tol=0.20,0.95   files mbb
TABLE   crs_mesh_blk_line            key=id          row_tol=0.20,0.95   files mbl1
TABLE   crs_mesh_blk_place           key=audit_id    row_tol=0.20,0.95   files mpl
```

Heres a [listing](https://gist.github.com/palmerj/91ef719c8cc4cea4d43ae2f3fc3202bf) of the latest level_0 BDE to confirm what files are unloaded now.

> It might help to drop a link here about the simplified electoral layers as found in AIMS \cc @SPlanzer 

No reason to import outside data into the BDE Processor database once the electoral support is dropped. In the future if we implement #14, which local government (TAs) customers have asked for in the past, then we would need to source territorial admin boundary data again. But maybe that could be done differently once the new admin boundaries uploader is finished.

**Comment by strk** [comment]
The `mesh_blocks` table maintainance code has been already removed from this schema 3 days ago via #51.  I'm happy to review a PR dropping the LDS.LDS_MaintainSimplifiedElectoralLayers too, if you think @billgeo is the best person to do this. Or I can try it myself if @imincik agrees.

I guess we'll need to specify which version of LoL  is supported by which branch, the current README doesn't say anything about it.

**Comment by palmerj** [comment]
> the current README doesn't say anything about it.

Yes starting from version support matrix might be of help

**Comment by strk** [comment]
From face2face meeting @palmerj confirmed we can just DROP the dependency.
I'll make a PR to drop MaintainSimplifiedElectoralLayers etc.
