### ISSUE TITLE
Hydro Parcels being missed by BDE processor

### ISSUE THREAD

**Issue by iharrison** [linz/linz-lds-bde-schema#46]
A LDS user has identified a bug in the LDS parcel layers. Turns out that hydro parcels are not only determined by parcel intent ='hydro' but also the following parcel intents are valid for hydro:
'VCMC', 'VDCO ' and 'VDLA' 
(Common Marine and Coastal Area (Sec 237A(1)(b) RM Act), Vesting on Deposit in the Crown (Sec 239(1)(c) RM Act) and Vesting on Deposit in the Territorial Authority Sec 237A(1)(a) RM Act respectively).

Need to check all the code that select only hydro parcels and add these three cases.
@billgeo @palmerj @imincik please advise what branch should this change be made in? Also how can we test?

- [ ] test once released - IH

**Comment by billgeo** [comment]
Hey @IReese, currently maintaining LDS code here. https://github.com/linz/linz_bde_uploader_private/tree/release_1_5

If you want to make changes hold fire for a day or so. Just discussing whether to merge this back to master or not with @palmerj and @imincik. See https://github.com/linz/linz_bde_uploader_private/pull/17

**Comment by iharrison** [comment]
Thanks @billgeo 

FYI there's 386 parcels affected.

**Comment by billgeo** [comment]
Also testing, is on your machine. Have to set up a DB, connections to BDE server etc and then only process the tables you need via BDE tables config. Quite a palaver.

And then when ready to deploy can ask Kx to test on the BDE Test server.

**Comment by iharrison** [comment]
Could this be bundled with another change?

**Comment by billgeo** [comment]
I can maybe look at this next week. How urgent a problem is this for customers?

**Comment by iharrison** [comment]
The customer who noticed it was "very concerned". But there's 380 odd parcels out of 2.5 million so...

**Comment by strk** [comment]
FYI: bde-processor-deployment has a test comparing a dump
of the data in the LDS schema tables after import of BDE
datasets 20150701 and 20160402. The expected dumps are
downloaded from S3, so testing any change in the functions
populating those "simplified" layers would imply:

 1) Download bde_sample_data_small.tar.gz from S3 (linz-bde-data bucket)
 2) For each BDE dataset 20150606233300, 20160402183600:
    2.1) BDE-import dataset
    2.2) Manual testing to verify the obtained LDS table data are ok.
    2.3) Create a new dump (pg_dump --schema lds --data-only)
    2.4) Archive and upload dump to S3 (linz-bde-data bucket)
         with name template:
         bde_sample_data_small-expected_lds_data_YYYYMMDD.dump.tar.gz

Having local automated tests would be great but the functions
currently populating those tables depend on metadata written by
BDE upload process so it's not easy to setup "unit" testing.

Reworking the functions to allow easier calling could help in this
reguard.

**Comment by imincik** [comment]
> Hey @iharrison , currently maintaining LDS code here. https://github.com/linz/linz_bde_uploader_private/tree/release_1_5

@billgeo , this repo contains only `linz_bde_uploader`, if bug exists in `linz-lds-bde-schema` , then it has to be fixed here.

@iharrison , please create `46-missing-hydro-parcels-fix` branch from `master` branch, do changes and submit GitHub pull request. Assign it to me and @strk for review.

@iharrison , @billgeo , we have automated test running with small BDE data subset every day for `master` branch and latest release branches of all BDE Processor components.

**Comment by billgeo** [comment]
Hey @imincik and @iharrison to get this change on to the LDS we will also have to make the change here. Unfortunately maintaining all this in two places at the moment.

https://github.com/linz/linz_bde_uploader_private/blob/e31541df811713b0c174dea7cc4b96979706fd38/sql/lds_layer_functions.sql#L2147

**Comment by iharrison** [comment]
Thanks @billgeo, I'll make the change there too.

**Comment by iharrison** [comment]
@imincik @billgeo created branch '46-missing-hydro-parcels-fix' of release_1_5 but then thought better of it. Please advise if better to create branch from master once release_1_5 is merged back.

**Comment by strk** [comment]
Is there anything we can do to avoid the duplicated code ?
I saw that `linz-lds-bde-schema` for example relies on functions being overridden by a `linz-lds-bde-schema-private` repository, for example, so that there's no duplication (the public version of the sensitive function is just a stub)

**Comment by palmerj** [comment]
> Is there anything we can do to avoid the duplicated code ?

Do you mean the parallel version of the whole BDE processor codebase in https://github.com/linz/linz_bde_uploader_private? If so then the only way is move the production LDS and test BDE install to the new versions you have been developement

**Comment by billgeo** [comment]
Nesha has raised a jira to discuss moving LDS new to new version sooner than planned. Will discuss there. 

For now will make this change in both places and release to LDS bde processor next week

**Comment by billgeo** [comment]
Kx support ticket here. https://support.koordinates.com/hc/en-us/requests/9778

**Comment by billgeo** [comment]
Hey @iharrison can you please commit your changes to that branch off release_1_5? @imincik is going to sort out the PR to master soon and then we can add this after I think. But better to have it there than not.

**Comment by imincik** [comment]
> @imincik @billgeo created branch '46-missing-hydro-parcels-fix' of release_1_5 but then thought better of it. Please advise if better to create branch from master once release_1_5 is merged back.

@iharrison , we probably want to merge this patch to `release_1_5` branch. So please create `46-missing-hydro-parcels-fix` from `release_1_5`
