### ISSUE TITLE
Add table comments

### ISSUE THREAD

**Issue by strk** [linz/linz-lds-bde-schema#57]
From https://github.com/linz/linz-bde-schema/issues/54#issuecomment-347316333 

> All of lds.* tables are defined in this data dictionary:                                      
> https://data.linz.govt.nz/document/11012-property-and-ownership-simplified-tables-data-dictionary/

We should add COMMENT ON snippets to tables from that source.

**Comment by strk** [comment]
Do we have an XML form for this information too ?

**Comment by palmerj** [comment]
As per the table data only the Internal Landonline Data Dictionary is in XML. The LDS simple and LDS Full Landonline data dictionaries are in PDF.

**Comment by palmerj** [comment]
I think the better longer term solution is to work on this: https://github.com/linz/ds-lds-geospatial-tasks/issues/257

**Comment by strk** [comment]
For the record: this task is being worked on in #73

**Comment by strk** [comment]
PR was merged, we do have table comments now.

**Comment by imincik** [comment]
Thanks @strk
