### ISSUE TITLE
 [debian] drop package dependency on PostgreSQL/PostGIS/dbpatch

### ISSUE THREAD

**Issue by strk** [linz/linz-lds-bde-schema#58]
The linz-lds-bde-schema files are not strictly dependent on postgresql/postgis/dbpatch/tableversion because all of them are only required to be on the *target* database system, not necessarely the same as the system from which linz-bde-schema is installed.

See also https://github.com/linz/linz_bde_uploader/issues/141
and https://github.com/linz/linz-bde-schema/issues/55

**Comment by strk** [comment]
The `check` Makefile rule currently depends on `pg_regress` which is shipped as part of `postgresql-server-dev` as far as I can tell.

**Comment by imincik** [comment]
Thanks @strk
