### ISSUE TITLE
Implement/Update tests

### ISSUE THREAD

**Issue by imincik** [linz/linz-lds-bde-schema#6]
Implement/Update tests

**Comment by strk** [comment]
I think with 60f2e857bac84f827ddbeb0701024cbf1b2bd7c8 the tests are good enough.
They check for existance and structure of tables, presence of indexes, versioned status of tables, presence of functions.

It would be good to have tests for actual functions *use* but may be better to address that in a second pass, after all BDE components are integrated to CI.
