### ISSUE TITLE
Switch tests to install dependencies from apt repository

### ISSUE THREAD

**Issue by strk** [linz/linz-lds-bde-schema#60]
At least dbpatch and table_version (see .travis.yml) but maybe also more.
We want to avoid having to use travis secrets though, so such repositories need to be public.
This needs to wait for packages to be available in a public PPA (dbpatch 1.2.0 and table_version 1.4.0).

See https://github.com/linz/linz-lds-bde-schema/pull/54#issuecomment-347898249

**Comment by imincik** [comment]
All packages which are coming from public GitHub repo are copied to public PPA
