### ISSUE TITLE
Add Debian Packaging Dependency for linz-bde-schema

### ISSUE THREAD

**Issue by palmerj** [linz/linz-lds-bde-schema#71]
The Debian packaging for linz-lds-bde-schema doesn't have a dependency on linz-bde-schema. I think we should change that because linz-lds-bde-schema functions definitely needs to use datasets from the bde schema which are only provided by linz-bde-schema.

**Comment by strk** [comment]
See commit e82dc89438c1af33c60f434e3e599ffe37ef3b90 for a background.

**Comment by strk** [comment]
I've moved linz-bde-schema back from Recommended to Depends as part of https://github.com/linz/linz-lds-bde-schema/pull/78

**Comment by imincik** [comment]
Thanks @strk
