### ISSUE TITLE
Publish debian package for 1.1.0 to "production" apt repository

### ISSUE THREAD

**Issue by strk** [linz/linz-lds-bde-schema#72]
It is needed to succeed at upload when territorial boundaries are not available in target database.

**Comment by imincik** [comment]
@strk are you after promoting some package from test branch to prod ? You should have rights to do it, see: https://github.com/linz/linz-software-repository/wiki/Debian-packaging#production-branch-promotion

**Comment by strk** [comment]
yes, that's what this ticket is about. Is assigned to myself, filed it now that I confirm it's needed to succeed bde-processor w/out using testing repo

**Comment by strk** [comment]
Promoted
