### ISSUE TITLE
MaintainSimplifiedLayers and friend have too much dependency on linz-bde-uploader-schema

### ISSUE THREAD

**Issue by strk** [linz/linz-lds-bde-schema#94]
The MaintainSimplifiedLayers function and friends have a huge dependency on schema objects installed by linz-bde-uploader for the sole purpose of skipping a run IFF none of the input tables were changed during the _current_ upload task. This also means that running those functions _require_ a _current_ upload to exist, making it impossible to test them outside of a full upload transaction (which implies creation of a temporary schema, among other things).

This ticket is to think of ways to reduce or drop the dependency, maybe by splitting the functions between a checking and a non-checking part and only testing the non-checking part.

**Comment by imincik** [comment]
+1 from me to solve it :)

**Comment by strk** [comment]
From https://github.com/linz/bde-processor-deployment/issues/243#issuecomment-398720301 the idea refined into dividing those functions in a checking and a non-checking version but move the checking version _outside_ of this repository and into the linz-bde-uploader repository, to completely drop the dependency.

I'll keep this ticket for implementing the non-checking version.
The checking version could be a DO block in the configuration for [linz-bde-uploader](https://github.com/linz/linz_bde_uploader)

**Comment by palmerj** [comment]
Maybe an idea here is we merge the linz-bde-uploader, linz-bde-schema and linz-lds-bde-schema back together again once the NG BDE Processor replication support feature is added. The only reason why we split this packages up in the first place was to allow for different BDE Processor installs. @ccrook does have some dependencies on linz-bde-schema in some of his geodetic packages, but I think those could be refactored to copy and paste the schemas required for geodetic during the NG BDE Processor replication feature work

**Comment by strk** [comment]
Another dependency spotted: function `bde_control.bde_expandTemplate` is used by `MaintainSimplifiedLayers` and friends

**Comment by strk** [comment]
This issue is mitigated by the enhancement in #155, about to be merged.
The dependency issue still exists, but it will harm less
